// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/alex/AnalizadorLexico.flex

package alex;

import errors.GestionErrores;
import constructorast.ClaseLexica;


@SuppressWarnings("fallthrough")
public class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\2\1\1\2\2\0\1\1\22\0\1\1\2\0"+
    "\1\3\2\0\1\4\1\0\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\12\15\1\16\1\17\1\20"+
    "\1\21\1\22\2\0\32\23\1\24\1\0\1\25\1\0"+
    "\1\23\1\0\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\23\1\34\1\35\2\23\1\36\1\23\1\37\1\40"+
    "\1\41\1\23\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\23\1\50\1\23\1\51\1\0\1\52\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\15\22\1\25\1\26"+
    "\22\2\1\27\1\0\1\30\7\22\1\31\2\22\1\32"+
    "\1\33\6\22\1\34\1\35\1\36\6\22\1\37\1\40"+
    "\4\22\1\41\3\22\1\42\1\22\1\43\1\22\1\44"+
    "\1\22\1\45\1\46\1\22\1\47\1\50\1\22\1\51"+
    "\1\52\1\53\1\54\1\22\1\55\1\56";

  private static int [] zzUnpackAction() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\126\0\201\0\126\0\126\0\126"+
    "\0\126\0\126\0\126\0\126\0\126\0\254\0\327\0\126"+
    "\0\126\0\126\0\u0102\0\126\0\u012d\0\126\0\126\0\u0158"+
    "\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a\0\u0285\0\u02b0"+
    "\0\u02db\0\u0306\0\u0331\0\u035c\0\126\0\126\0\u0387\0\254"+
    "\0\327\0\u0102\0\u012d\0\u0158\0\u0183\0\u01ae\0\u01d9\0\u0204"+
    "\0\u022f\0\u025a\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c"+
    "\0\126\0\u03b2\0\126\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489"+
    "\0\u04b4\0\u04df\0\u012d\0\u050a\0\u0535\0\u012d\0\u012d\0\u0560"+
    "\0\u058b\0\u05b6\0\u05e1\0\u060c\0\u0637\0\126\0\u03b2\0\u012d"+
    "\0\u0662\0\u068d\0\u06b8\0\u06e3\0\u070e\0\u0739\0\u012d\0\u012d"+
    "\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u012d\0\u0810\0\u083b\0\u0866"+
    "\0\u012d\0\u0891\0\u012d\0\u08bc\0\u012d\0\u08e7\0\u012d\0\u012d"+
    "\0\u0912\0\u012d\0\u012d\0\u093d\0\u012d\0\u012d\0\u012d\0\u012d"+
    "\0\u0968\0\u012d\0\u012d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\25\1\33\1\34\1\25\1\35\1\25\1\36\1\37"+
    "\1\40\1\41\1\25\1\42\1\25\1\43\1\44\1\25"+
    "\1\45\1\46\3\4\1\5\3\4\1\47\4\4\1\50"+
    "\1\51\3\4\1\52\1\4\1\53\2\4\1\54\1\55"+
    "\1\56\1\53\1\57\1\60\1\53\1\61\1\53\1\62"+
    "\1\63\1\64\1\65\1\53\1\66\1\53\1\67\1\70"+
    "\1\53\2\4\53\0\2\5\1\0\50\5\7\0\1\71"+
    "\56\0\1\72\1\0\1\17\56\0\1\73\46\0\1\25"+
    "\5\0\1\25\2\0\23\25\17\0\1\25\5\0\1\25"+
    "\2\0\11\25\1\74\2\25\1\75\6\25\17\0\1\25"+
    "\5\0\1\25\2\0\12\25\1\76\10\25\17\0\1\25"+
    "\5\0\1\25\2\0\10\25\1\77\12\25\17\0\1\25"+
    "\5\0\1\25\2\0\10\25\1\100\12\25\17\0\1\25"+
    "\5\0\1\25\2\0\1\101\16\25\1\102\3\25\17\0"+
    "\1\25\5\0\1\25\2\0\5\25\1\103\3\25\1\104"+
    "\11\25\17\0\1\25\5\0\1\25\2\0\4\25\1\105"+
    "\16\25\17\0\1\25\5\0\1\25\2\0\5\25\1\106"+
    "\6\25\1\107\6\25\17\0\1\25\5\0\1\25\2\0"+
    "\14\25\1\110\6\25\17\0\1\25\5\0\1\25\2\0"+
    "\4\25\1\111\16\25\17\0\1\25\5\0\1\25\2\0"+
    "\14\25\1\112\6\25\17\0\1\25\5\0\1\25\2\0"+
    "\1\113\11\25\1\114\10\25\17\0\1\25\5\0\1\25"+
    "\2\0\6\25\1\115\14\25\16\0\1\116\53\0\1\117"+
    "\52\0\1\25\5\0\1\25\2\0\3\25\1\120\17\25"+
    "\17\0\1\25\5\0\1\25\2\0\14\25\1\121\6\25"+
    "\17\0\1\25\5\0\1\25\2\0\12\25\1\122\10\25"+
    "\17\0\1\25\5\0\1\25\2\0\1\123\22\25\17\0"+
    "\1\25\5\0\1\25\2\0\15\25\1\124\5\25\17\0"+
    "\1\25\5\0\1\25\2\0\10\25\1\125\12\25\17\0"+
    "\1\25\5\0\1\25\2\0\11\25\1\126\11\25\17\0"+
    "\1\25\5\0\1\25\2\0\16\25\1\127\4\25\17\0"+
    "\1\25\5\0\1\25\2\0\21\25\1\130\1\25\17\0"+
    "\1\25\5\0\1\25\2\0\7\25\1\131\13\25\17\0"+
    "\1\25\5\0\1\25\2\0\1\132\15\25\1\133\4\25"+
    "\17\0\1\25\5\0\1\25\2\0\17\25\1\134\3\25"+
    "\17\0\1\25\5\0\1\25\2\0\14\25\1\135\6\25"+
    "\17\0\1\25\5\0\1\25\2\0\7\25\1\136\13\25"+
    "\17\0\1\25\5\0\1\25\2\0\7\25\1\137\13\25"+
    "\17\0\1\25\5\0\1\25\2\0\1\140\22\25\17\0"+
    "\1\25\5\0\1\25\2\0\10\25\1\141\12\25\17\0"+
    "\1\25\5\0\1\25\2\0\15\25\1\142\5\25\17\0"+
    "\1\25\5\0\1\25\2\0\4\25\1\143\16\25\17\0"+
    "\1\25\5\0\1\25\2\0\15\25\1\144\5\25\17\0"+
    "\1\25\5\0\1\25\2\0\2\25\1\145\20\25\17\0"+
    "\1\25\5\0\1\25\2\0\11\25\1\146\11\25\17\0"+
    "\1\25\5\0\1\25\2\0\3\25\1\147\4\25\1\150"+
    "\12\25\17\0\1\25\5\0\1\25\2\0\17\25\1\151"+
    "\3\25\17\0\1\25\5\0\1\25\2\0\4\25\1\152"+
    "\16\25\17\0\1\25\5\0\1\25\2\0\3\25\1\153"+
    "\17\25\17\0\1\25\5\0\1\25\2\0\10\25\1\154"+
    "\12\25\17\0\1\25\5\0\1\25\2\0\22\25\1\155"+
    "\17\0\1\25\5\0\1\25\2\0\15\25\1\156\5\25"+
    "\17\0\1\25\5\0\1\25\2\0\4\25\1\157\16\25"+
    "\17\0\1\25\5\0\1\25\2\0\16\25\1\160\4\25"+
    "\17\0\1\25\5\0\1\25\2\0\14\25\1\161\6\25"+
    "\17\0\1\25\5\0\1\25\2\0\4\25\1\162\16\25"+
    "\17\0\1\25\5\0\1\25\2\0\11\25\1\163\11\25"+
    "\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2451];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\1\1\10\11\2\1\3\11\1\1\1\11"+
    "\1\1\2\11\15\1\2\11\22\1\1\11\1\0\1\11"+
    "\22\1\1\11\45\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  private ALexOperations ops;
  private GestionErrores errores;
  public String lexema() {return yytext();}
  public int fila() {return yyline+1;}
  public int columna() {return yycolumn+1;}
  public void fijaGestionErrores(GestionErrores errores) {
   this.errores = errores;
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
    ops = new ALexOperations(this);
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {   return ops.unidad(ClaseLexica.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errores.errorLexico(fila(),columna(),lexema());
            }
          // fall through
          case 47: break;
          case 2:
            { 
            }
          // fall through
          case 48: break;
          case 3:
            { return ops.unidad(ClaseLexica.AMPERSAND);
            }
          // fall through
          case 49: break;
          case 4:
            { return ops.unidad(ClaseLexica.PARENTESIS_APERTURA);
            }
          // fall through
          case 50: break;
          case 5:
            { return ops.unidad(ClaseLexica.PARENTESIS_CIERRE);
            }
          // fall through
          case 51: break;
          case 6:
            { return ops.unidad(ClaseLexica.MULTIPLICACION);
            }
          // fall through
          case 52: break;
          case 7:
            { return ops.unidad(ClaseLexica.SUMA);
            }
          // fall through
          case 53: break;
          case 8:
            { return ops.unidad(ClaseLexica.COMA);
            }
          // fall through
          case 54: break;
          case 9:
            { return ops.unidad(ClaseLexica.RESTA);
            }
          // fall through
          case 55: break;
          case 10:
            { return ops.unidad(ClaseLexica.PUNTO);
            }
          // fall through
          case 56: break;
          case 11:
            { return ops.unidad(ClaseLexica.DIVISION);
            }
          // fall through
          case 57: break;
          case 12:
            { return ops.unidad(ClaseLexica.NUM, lexema());
            }
          // fall through
          case 58: break;
          case 13:
            { return ops.unidad(ClaseLexica.DOS_PUNTOS);
            }
          // fall through
          case 59: break;
          case 14:
            { return ops.unidad(ClaseLexica.PUNTO_Y_COMA);
            }
          // fall through
          case 60: break;
          case 15:
            { return ops.unidad(ClaseLexica.MENOR);
            }
          // fall through
          case 61: break;
          case 16:
            { return ops.unidad(ClaseLexica.IGUAL);
            }
          // fall through
          case 62: break;
          case 17:
            { return ops.unidad(ClaseLexica.MAYOR);
            }
          // fall through
          case 63: break;
          case 18:
            { return ops.unidad(ClaseLexica.ID, lexema());
            }
          // fall through
          case 64: break;
          case 19:
            { return ops.unidad(ClaseLexica.CORCHETE_APERTURA);
            }
          // fall through
          case 65: break;
          case 20:
            { return ops.unidad(ClaseLexica.CORCHETE_CIERRE);
            }
          // fall through
          case 66: break;
          case 21:
            { return ops.unidad(ClaseLexica.LLAVE_APERTURA);
            }
          // fall through
          case 67: break;
          case 22:
            { return ops.unidad(ClaseLexica.LLAVE_CIERRE);
            }
          // fall through
          case 68: break;
          case 23:
            { yybegin(COMMENT);
            }
          // fall through
          case 69: break;
          case 24:
            { return ops.unidad(ClaseLexica.IGUALDAD);
            }
          // fall through
          case 70: break;
          case 25:
            { return ops.unidad(ClaseLexica.IF);
            }
          // fall through
          case 71: break;
          case 26:
            { return ops.unidad(ClaseLexica.OF);
            }
          // fall through
          case 72: break;
          case 27:
            { return ops.unidad(ClaseLexica.OR);
            }
          // fall through
          case 73: break;
          case 28:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 74: break;
          case 29:
            { return ops.unidad(ClaseLexica.NUM_REAL, lexema());
            }
          // fall through
          case 75: break;
          case 30:
            { return ops.unidad(ClaseLexica.AND);
            }
          // fall through
          case 76: break;
          case 31:
            { return ops.unidad(ClaseLexica.INT);
            }
          // fall through
          case 77: break;
          case 32:
            { return ops.unidad(ClaseLexica.NEW);
            }
          // fall through
          case 78: break;
          case 33:
            { return ops.unidad(ClaseLexica.VAR);
            }
          // fall through
          case 79: break;
          case 34:
            { return ops.unidad(ClaseLexica.BOOL);
            }
          // fall through
          case 80: break;
          case 35:
            { return ops.unidad(ClaseLexica.ELSE);
            }
          // fall through
          case 81: break;
          case 36:
            { return ops.unidad(ClaseLexica.FUNC);
            }
          // fall through
          case 82: break;
          case 37:
            { return ops.unidad(ClaseLexica.READ);
            }
          // fall through
          case 83: break;
          case 38:
            { return ops.unidad(ClaseLexica.REAL);
            }
          // fall through
          case 84: break;
          case 39:
            { return ops.unidad(ClaseLexica.TRUE);
            }
          // fall through
          case 85: break;
          case 40:
            { return ops.unidad(ClaseLexica.VOID);
            }
          // fall through
          case 86: break;
          case 41:
            { return ops.unidad(ClaseLexica.ARRAY);
            }
          // fall through
          case 87: break;
          case 42:
            { return ops.unidad(ClaseLexica.CLASS);
            }
          // fall through
          case 88: break;
          case 43:
            { return ops.unidad(ClaseLexica.FALSE);
            }
          // fall through
          case 89: break;
          case 44:
            { return ops.unidad(ClaseLexica.PRINT);
            }
          // fall through
          case 90: break;
          case 45:
            { return ops.unidad(ClaseLexica.WHILE);
            }
          // fall through
          case 91: break;
          case 46:
            { return ops.unidad(ClaseLexica.RETURN);
            }
          // fall through
          case 92: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
