
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Apr 06 20:26:14 CEST 2026
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PARENTESIS_CIERRE = 14;
  public static final int PUNTO_Y_COMA = 4;
  public static final int RESTA = 24;
  public static final int DOS_PUNTOS = 3;
  public static final int INT = 19;
  public static final int ARRAY = 6;
  public static final int AND = 30;
  public static final int IGUAL = 5;
  public static final int CORCHETE_CIERRE = 16;
  public static final int IGUALDAD = 29;
  public static final int OR = 31;
  public static final int BOOL = 20;
  public static final int NUM = 38;
  public static final int SUMA = 23;
  public static final int IF = 32;
  public static final int AMPERSAND = 18;
  public static final int ID = 37;
  public static final int OF = 7;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int CORCHETE_APERTURA = 15;
  public static final int TRUE = 21;
  public static final int error = 1;
  public static final int COMA = 17;
  public static final int MENOR = 27;
  public static final int VOID = 11;
  public static final int MAYOR = 28;
  public static final int ELSE = 33;
  public static final int FUNC = 10;
  public static final int READ = 35;
  public static final int LLAVE_APERTURA = 8;
  public static final int WHILE = 34;
  public static final int LLAVE_CIERRE = 9;
  public static final int PARENTESIS_APERTURA = 13;
  public static final int FALSE = 22;
  public static final int DIVISION = 26;
  public static final int VAR = 2;
  public static final int PRINT = 36;
  public static final int MULTIPLICACION = 25;
}

