
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue May 05 17:30:15 CEST 2026
//----------------------------------------------------

package constructorast;

import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.List;
import alex.AnalizadorLexico;
import alex.UnidadLexica;
import errors.GestionErrores;
import ast.*;
import java_cup.runtime.ComplexSymbolFactory.Location;

/** CUP v0.11b beta 20140220 generated parser.
  * @version Tue May 05 17:30:15 CEST 2026
  */
public class ConstructorAST extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ConstructorAST() {super();}

  /** Constructor which sets the default scanner. */
  public ConstructorAST(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ConstructorAST(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\123\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\003\000\002\005\003\000\002\005" +
    "\003\000\002\010\007\000\002\010\011\000\002\011\012" +
    "\000\002\012\010\000\002\013\004\000\002\013\004\000" +
    "\002\013\002\000\002\014\003\000\002\014\003\000\002" +
    "\014\003\000\002\014\003\000\002\014\006\000\002\014" +
    "\003\000\002\015\006\000\002\015\005\000\002\016\003" +
    "\000\002\016\002\000\002\017\005\000\002\017\003\000" +
    "\002\020\006\000\002\020\007\000\002\006\005\000\002" +
    "\007\004\000\002\007\002\000\002\021\006\000\002\022" +
    "\007\000\002\022\011\000\002\023\003\000\002\023\006" +
    "\000\002\023\005\000\002\024\007\000\002\024\011\000" +
    "\002\025\007\000\002\026\007\000\002\027\007\000\002" +
    "\030\005\000\002\030\004\000\002\031\003\000\002\032" +
    "\005\000\002\032\003\000\002\033\005\000\002\033\003" +
    "\000\002\034\005\000\002\034\005\000\002\034\005\000" +
    "\002\034\003\000\002\035\005\000\002\035\005\000\002" +
    "\035\003\000\002\036\005\000\002\036\005\000\002\036" +
    "\003\000\002\037\004\000\002\037\003\000\002\040\003" +
    "\000\002\040\003\000\002\040\003\000\002\040\003\000" +
    "\002\040\003\000\002\040\006\000\002\040\010\000\002" +
    "\040\007\000\002\040\005\000\002\041\003\000\002\041" +
    "\002\000\002\042\005\000\002\042\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\250\000\026\004\035\012\033\014\023\016\013\043" +
    "\016\045\011\046\005\047\025\050\007\053\017\001\002" +
    "\000\030\002\ufffd\004\ufffd\012\ufffd\014\ufffd\016\ufffd\043" +
    "\ufffd\045\ufffd\046\ufffd\047\ufffd\050\ufffd\053\ufffd\001\002" +
    "\000\004\017\247\001\002\000\032\002\ufff8\004\ufff8\012" +
    "\ufff8\013\ufff8\014\ufff8\016\ufff8\043\ufff8\045\ufff8\046\ufff8" +
    "\047\ufff8\050\ufff8\053\ufff8\001\002\000\004\005\240\001" +
    "\002\000\030\002\ufffe\004\ufffe\012\ufffe\014\ufffe\016\ufffe" +
    "\043\ufffe\045\ufffe\046\ufffe\047\ufffe\050\ufffe\053\ufffe\001" +
    "\002\000\004\017\234\001\002\000\030\002\ufffc\004\ufffc" +
    "\012\ufffc\014\ufffc\016\ufffc\043\ufffc\045\ufffc\046\ufffc\047" +
    "\ufffc\050\ufffc\053\ufffc\001\002\000\024\006\232\017\102" +
    "\030\071\031\073\033\101\051\065\053\074\054\062\055" +
    "\064\001\002\000\032\002\ufff7\004\ufff7\012\ufff7\013\ufff7" +
    "\014\ufff7\016\ufff7\043\ufff7\045\ufff7\046\ufff7\047\ufff7\050" +
    "\ufff7\053\ufff7\001\002\000\032\002\ufff5\004\ufff5\012\ufff5" +
    "\013\ufff5\014\ufff5\016\ufff5\043\ufff5\045\ufff5\046\ufff5\047" +
    "\ufff5\050\ufff5\053\ufff5\001\002\000\004\017\223\001\002" +
    "\000\012\007\uffd6\017\217\021\uffd6\052\uffd6\001\002\000" +
    "\032\002\ufff4\004\ufff4\012\ufff4\013\ufff4\014\ufff4\016\ufff4" +
    "\043\ufff4\045\ufff4\046\ufff4\047\ufff4\050\ufff4\053\ufff4\001" +
    "\002\000\004\002\216\001\002\000\032\002\ufff2\004\ufff2" +
    "\012\ufff2\013\ufff2\014\ufff2\016\ufff2\043\ufff2\045\ufff2\046" +
    "\ufff2\047\ufff2\050\ufff2\053\ufff2\001\002\000\016\010\044" +
    "\015\042\025\043\026\037\027\041\053\036\001\002\000" +
    "\010\007\165\021\135\052\164\001\002\000\004\017\160" +
    "\001\002\000\030\002\000\004\035\012\033\014\023\016" +
    "\013\043\016\045\011\046\005\047\025\050\007\053\017" +
    "\001\002\000\032\002\ufff6\004\ufff6\012\ufff6\013\ufff6\014" +
    "\ufff6\016\ufff6\043\ufff6\045\ufff6\046\ufff6\047\ufff6\050\ufff6" +
    "\053\ufff6\001\002\000\032\002\ufff9\004\ufff9\012\ufff9\013" +
    "\ufff9\014\ufff9\016\ufff9\043\ufff9\045\ufff9\046\ufff9\047\ufff9" +
    "\050\ufff9\053\ufff9\001\002\000\032\002\ufff3\004\ufff3\012" +
    "\ufff3\013\ufff3\014\ufff3\016\ufff3\043\ufff3\045\ufff3\046\ufff3" +
    "\047\ufff3\050\ufff3\053\ufff3\001\002\000\032\002\ufffa\004" +
    "\ufffa\012\ufffa\013\ufffa\014\ufffa\016\ufffa\043\ufffa\045\ufffa" +
    "\046\ufffa\047\ufffa\050\ufffa\053\ufffa\001\002\000\024\004" +
    "\uffda\012\uffda\013\uffda\016\uffda\043\uffda\045\uffda\046\uffda" +
    "\047\uffda\053\uffda\001\002\000\030\002\ufffb\004\ufffb\012" +
    "\ufffb\014\ufffb\016\ufffb\043\ufffb\045\ufffb\046\ufffb\047\ufffb" +
    "\050\ufffb\053\ufffb\001\002\000\016\010\044\015\042\025" +
    "\043\026\037\027\041\053\036\001\002\000\004\005\uffe5" +
    "\001\002\000\004\005\uffe9\001\002\000\004\005\056\001" +
    "\002\000\004\005\uffe8\001\002\000\004\005\uffe7\001\002" +
    "\000\004\005\uffea\001\002\000\004\021\046\001\002\000" +
    "\006\011\052\021\051\001\002\000\004\054\047\001\002" +
    "\000\004\022\050\001\002\000\006\011\uffe3\021\uffe3\001" +
    "\002\000\004\054\054\001\002\000\016\010\044\015\042" +
    "\025\043\026\037\027\041\053\036\001\002\000\004\005" +
    "\uffe6\001\002\000\004\022\055\001\002\000\006\011\uffe4" +
    "\021\uffe4\001\002\000\004\053\057\001\002\000\006\006" +
    "\061\007\060\001\002\000\022\017\102\030\071\031\073" +
    "\033\101\051\065\053\074\054\062\055\064\001\002\000" +
    "\032\002\ufff1\004\ufff1\012\ufff1\013\ufff1\014\ufff1\016\ufff1" +
    "\043\ufff1\045\ufff1\046\ufff1\047\ufff1\050\ufff1\053\ufff1\001" +
    "\002\000\034\006\uffbb\020\uffbb\022\uffbb\023\uffbb\032\uffbb" +
    "\033\uffbb\034\uffbb\035\uffbb\036\uffbb\037\uffbb\040\uffbb\041" +
    "\uffbb\042\uffbb\001\002\000\034\006\uffc1\020\uffc1\022\uffc1" +
    "\023\uffc1\032\uffc1\033\uffc1\034\112\035\113\036\uffc1\037" +
    "\uffc1\040\uffc1\041\uffc1\042\uffc1\001\002\000\034\006\uffba" +
    "\020\uffba\022\uffba\023\uffba\032\uffba\033\uffba\034\uffba\035" +
    "\uffba\036\uffba\037\uffba\040\uffba\041\uffba\042\uffba\001\002" +
    "\000\004\053\150\001\002\000\016\006\uffca\020\uffca\022" +
    "\uffca\023\uffca\041\146\042\uffca\001\002\000\014\006\uffcc" +
    "\020\uffcc\022\uffcc\023\uffcc\042\144\001\002\000\040\006" +
    "\uffb7\020\uffb7\021\135\022\uffb7\023\uffb7\032\uffb7\033\uffb7" +
    "\034\uffb7\035\uffb7\036\uffb7\037\uffb7\040\uffb7\041\uffb7\042" +
    "\uffb7\052\134\001\002\000\034\006\uffb9\020\uffb9\022\uffb9" +
    "\023\uffb9\032\uffb9\033\uffb9\034\uffb9\035\uffb9\036\uffb9\037" +
    "\uffb9\040\uffb9\041\uffb9\042\uffb9\001\002\000\034\006\uffbe" +
    "\020\uffbe\022\uffbe\023\uffbe\032\uffbe\033\uffbe\034\uffbe\035" +
    "\uffbe\036\uffbe\037\uffbe\040\uffbe\041\uffbe\042\uffbe\001\002" +
    "\000\034\006\uffb8\020\uffb8\022\uffb8\023\uffb8\032\uffb8\033" +
    "\uffb8\034\uffb8\035\uffb8\036\uffb8\037\uffb8\040\uffb8\041\uffb8" +
    "\042\uffb8\001\002\000\042\006\uffd6\017\125\020\uffd6\021" +
    "\uffd6\022\uffd6\023\uffd6\032\uffd6\033\uffd6\034\uffd6\035\uffd6" +
    "\036\uffd6\037\uffd6\040\uffd6\041\uffd6\042\uffd6\052\uffd6\001" +
    "\002\000\024\006\uffc8\020\uffc8\022\uffc8\023\uffc8\036\117" +
    "\037\121\040\120\041\uffc8\042\uffc8\001\002\000\030\006" +
    "\uffc4\020\uffc4\022\uffc4\023\uffc4\032\110\033\107\036\uffc4" +
    "\037\uffc4\040\uffc4\041\uffc4\042\uffc4\001\002\000\034\006" +
    "\uffbc\020\uffbc\022\uffbc\023\uffbc\032\uffbc\033\uffbc\034\uffbc" +
    "\035\uffbc\036\uffbc\037\uffbc\040\uffbc\041\uffbc\042\uffbc\001" +
    "\002\000\004\006\106\001\002\000\022\017\102\030\071" +
    "\031\073\033\101\051\065\053\074\054\062\055\064\001" +
    "\002\000\022\017\102\030\071\031\073\033\101\051\065" +
    "\053\074\054\062\055\064\001\002\000\004\020\104\001" +
    "\002\000\034\006\uffb3\020\uffb3\022\uffb3\023\uffb3\032\uffb3" +
    "\033\uffb3\034\uffb3\035\uffb3\036\uffb3\037\uffb3\040\uffb3\041" +
    "\uffb3\042\uffb3\001\002\000\034\006\uffbd\020\uffbd\022\uffbd" +
    "\023\uffbd\032\uffbd\033\uffbd\034\uffbd\035\uffbd\036\uffbd\037" +
    "\uffbd\040\uffbd\041\uffbd\042\uffbd\001\002\000\032\002\ufff0" +
    "\004\ufff0\012\ufff0\013\ufff0\014\ufff0\016\ufff0\043\ufff0\045" +
    "\ufff0\046\ufff0\047\ufff0\050\ufff0\053\ufff0\001\002\000\022" +
    "\017\102\030\071\031\073\033\101\051\065\053\074\054" +
    "\062\055\064\001\002\000\022\017\102\030\071\031\073" +
    "\033\101\051\065\053\074\054\062\055\064\001\002\000" +
    "\034\006\uffc3\020\uffc3\022\uffc3\023\uffc3\032\uffc3\033\uffc3" +
    "\034\112\035\113\036\uffc3\037\uffc3\040\uffc3\041\uffc3\042" +
    "\uffc3\001\002\000\022\017\102\030\071\031\073\033\101" +
    "\051\065\053\074\054\062\055\064\001\002\000\022\017" +
    "\102\030\071\031\073\033\101\051\065\053\074\054\062" +
    "\055\064\001\002\000\034\006\uffbf\020\uffbf\022\uffbf\023" +
    "\uffbf\032\uffbf\033\uffbf\034\uffbf\035\uffbf\036\uffbf\037\uffbf" +
    "\040\uffbf\041\uffbf\042\uffbf\001\002\000\034\006\uffc0\020" +
    "\uffc0\022\uffc0\023\uffc0\032\uffc0\033\uffc0\034\uffc0\035\uffc0" +
    "\036\uffc0\037\uffc0\040\uffc0\041\uffc0\042\uffc0\001\002\000" +
    "\034\006\uffc2\020\uffc2\022\uffc2\023\uffc2\032\uffc2\033\uffc2" +
    "\034\112\035\113\036\uffc2\037\uffc2\040\uffc2\041\uffc2\042" +
    "\uffc2\001\002\000\022\017\102\030\071\031\073\033\101" +
    "\051\065\053\074\054\062\055\064\001\002\000\022\017" +
    "\102\030\071\031\073\033\101\051\065\053\074\054\062" +
    "\055\064\001\002\000\022\017\102\030\071\031\073\033" +
    "\101\051\065\053\074\054\062\055\064\001\002\000\030" +
    "\006\uffc6\020\uffc6\022\uffc6\023\uffc6\032\110\033\107\036" +
    "\uffc6\037\uffc6\040\uffc6\041\uffc6\042\uffc6\001\002\000\030" +
    "\006\uffc5\020\uffc5\022\uffc5\023\uffc5\032\110\033\107\036" +
    "\uffc5\037\uffc5\040\uffc5\041\uffc5\042\uffc5\001\002\000\030" +
    "\006\uffc7\020\uffc7\022\uffc7\023\uffc7\032\110\033\107\036" +
    "\uffc7\037\uffc7\040\uffc7\041\uffc7\042\uffc7\001\002\000\024" +
    "\017\102\020\uffb1\030\071\031\073\033\101\051\065\053" +
    "\074\054\062\055\064\001\002\000\006\020\uffaf\023\uffaf" +
    "\001\002\000\004\020\133\001\002\000\006\020\uffb2\023" +
    "\131\001\002\000\022\017\102\030\071\031\073\033\101" +
    "\051\065\053\074\054\062\055\064\001\002\000\006\020" +
    "\uffb0\023\uffb0\001\002\000\034\006\uffb6\020\uffb6\022\uffb6" +
    "\023\uffb6\032\uffb6\033\uffb6\034\uffb6\035\uffb6\036\uffb6\037" +
    "\uffb6\040\uffb6\041\uffb6\042\uffb6\001\002\000\004\053\140" +
    "\001\002\000\022\017\102\030\071\031\073\033\101\051" +
    "\065\053\074\054\062\055\064\001\002\000\004\022\137" +
    "\001\002\000\042\006\uffd5\007\uffd5\020\uffd5\021\uffd5\022" +
    "\uffd5\023\uffd5\032\uffd5\033\uffd5\034\uffd5\035\uffd5\036\uffd5" +
    "\037\uffd5\040\uffd5\041\uffd5\042\uffd5\052\uffd5\001\002\000" +
    "\042\006\uffd4\017\141\020\uffd4\021\uffd4\022\uffd4\023\uffd4" +
    "\032\uffd4\033\uffd4\034\uffd4\035\uffd4\036\uffd4\037\uffd4\040" +
    "\uffd4\041\uffd4\042\uffd4\052\uffd4\001\002\000\024\017\102" +
    "\020\uffb1\030\071\031\073\033\101\051\065\053\074\054" +
    "\062\055\064\001\002\000\004\020\143\001\002\000\034" +
    "\006\uffb5\020\uffb5\022\uffb5\023\uffb5\032\uffb5\033\uffb5\034" +
    "\uffb5\035\uffb5\036\uffb5\037\uffb5\040\uffb5\041\uffb5\042\uffb5" +
    "\001\002\000\022\017\102\030\071\031\073\033\101\051" +
    "\065\053\074\054\062\055\064\001\002\000\016\006\uffcb" +
    "\020\uffcb\022\uffcb\023\uffcb\041\146\042\uffcb\001\002\000" +
    "\022\017\102\030\071\031\073\033\101\051\065\053\074" +
    "\054\062\055\064\001\002\000\024\006\uffc9\020\uffc9\022" +
    "\uffc9\023\uffc9\036\117\037\121\040\120\041\uffc9\042\uffc9" +
    "\001\002\000\004\017\151\001\002\000\024\017\102\020" +
    "\uffb1\030\071\031\073\033\101\051\065\053\074\054\062" +
    "\055\064\001\002\000\004\020\153\001\002\000\034\006" +
    "\uffb4\020\uffb4\022\uffb4\023\uffb4\032\uffb4\033\uffb4\034\uffb4" +
    "\035\uffb4\036\uffb4\037\uffb4\040\uffb4\041\uffb4\042\uffb4\001" +
    "\002\000\024\004\035\012\033\013\155\016\013\043\016" +
    "\045\011\046\005\047\025\053\017\001\002\000\034\002" +
    "\uffdc\004\uffdc\012\uffdc\013\uffdc\014\uffdc\016\uffdc\043\uffdc" +
    "\044\uffdc\045\uffdc\046\uffdc\047\uffdc\050\uffdc\053\uffdc\001" +
    "\002\000\024\004\uffdb\012\uffdb\013\uffdb\016\uffdb\043\uffdb" +
    "\045\uffdb\046\uffdb\047\uffdb\053\uffdb\001\002\000\030\002" +
    "\uffff\004\uffff\012\uffff\014\uffff\016\uffff\043\uffff\045\uffff" +
    "\046\uffff\047\uffff\050\uffff\053\uffff\001\002\000\022\017" +
    "\102\030\071\031\073\033\101\051\065\053\074\054\062" +
    "\055\064\001\002\000\004\020\162\001\002\000\004\006" +
    "\163\001\002\000\032\002\uffcf\004\uffcf\012\uffcf\013\uffcf" +
    "\014\uffcf\016\uffcf\043\uffcf\045\uffcf\046\uffcf\047\uffcf\050" +
    "\uffcf\053\uffcf\001\002\000\004\053\170\001\002\000\022" +
    "\017\102\030\071\031\073\033\101\051\065\053\074\054" +
    "\062\055\064\001\002\000\004\006\167\001\002\000\032" +
    "\002\uffd9\004\uffd9\012\uffd9\013\uffd9\014\uffd9\016\uffd9\043" +
    "\uffd9\045\uffd9\046\uffd9\047\uffd9\050\uffd9\053\uffd9\001\002" +
    "\000\012\007\uffd4\017\171\021\uffd4\052\uffd4\001\002\000" +
    "\024\017\102\020\uffb1\030\071\031\073\033\101\051\065" +
    "\053\074\054\062\055\064\001\002\000\004\020\173\001" +
    "\002\000\004\006\174\001\002\000\032\002\uffd7\004\uffd7" +
    "\012\uffd7\013\uffd7\014\uffd7\016\uffd7\043\uffd7\045\uffd7\046" +
    "\uffd7\047\uffd7\050\uffd7\053\uffd7\001\002\000\004\005\176" +
    "\001\002\000\004\053\177\001\002\000\004\017\200\001" +
    "\002\000\006\004\201\020\uffe1\001\002\000\016\010\044" +
    "\015\042\025\043\026\037\027\041\053\036\001\002\000" +
    "\006\020\uffe2\023\207\001\002\000\004\020\205\001\002" +
    "\000\006\020\uffdf\023\uffdf\001\002\000\004\012\033\001" +
    "\002\000\032\002\uffef\004\uffef\012\uffef\013\uffef\014\uffef" +
    "\016\uffef\043\uffef\045\uffef\046\uffef\047\uffef\050\uffef\053" +
    "\uffef\001\002\000\004\004\201\001\002\000\006\020\uffe0" +
    "\023\uffe0\001\002\000\004\005\212\001\002\000\006\024" +
    "\214\053\213\001\002\000\006\020\uffde\023\uffde\001\002" +
    "\000\004\053\215\001\002\000\006\020\uffdd\023\uffdd\001" +
    "\002\000\004\002\001\001\002\000\024\017\102\020\uffb1" +
    "\030\071\031\073\033\101\051\065\053\074\054\062\055" +
    "\064\001\002\000\004\020\221\001\002\000\004\006\222" +
    "\001\002\000\032\002\uffd8\004\uffd8\012\uffd8\013\uffd8\014" +
    "\uffd8\016\uffd8\043\uffd8\045\uffd8\046\uffd8\047\uffd8\050\uffd8" +
    "\053\uffd8\001\002\000\022\017\102\030\071\031\073\033" +
    "\101\051\065\053\074\054\062\055\064\001\002\000\004" +
    "\020\225\001\002\000\004\012\033\001\002\000\034\002" +
    "\uffd3\004\uffd3\012\uffd3\013\uffd3\014\uffd3\016\uffd3\043\uffd3" +
    "\044\227\045\uffd3\046\uffd3\047\uffd3\050\uffd3\053\uffd3\001" +
    "\002\000\004\012\033\001\002\000\032\002\uffd2\004\uffd2" +
    "\012\uffd2\013\uffd2\014\uffd2\016\uffd2\043\uffd2\045\uffd2\046" +
    "\uffd2\047\uffd2\050\uffd2\053\uffd2\001\002\000\004\006\233" +
    "\001\002\000\032\002\uffcd\004\uffcd\012\uffcd\013\uffcd\014" +
    "\uffcd\016\uffcd\043\uffcd\045\uffcd\046\uffcd\047\uffcd\050\uffcd" +
    "\053\uffcd\001\002\000\032\002\uffce\004\uffce\012\uffce\013" +
    "\uffce\014\uffce\016\uffce\043\uffce\045\uffce\046\uffce\047\uffce" +
    "\050\uffce\053\uffce\001\002\000\022\017\102\030\071\031" +
    "\073\033\101\051\065\053\074\054\062\055\064\001\002" +
    "\000\004\020\236\001\002\000\004\012\033\001\002\000" +
    "\032\002\uffd1\004\uffd1\012\uffd1\013\uffd1\014\uffd1\016\uffd1" +
    "\043\uffd1\045\uffd1\046\uffd1\047\uffd1\050\uffd1\053\uffd1\001" +
    "\002\000\004\053\241\001\002\000\004\012\242\001\002" +
    "\000\010\004\uffeb\013\uffeb\014\uffeb\001\002\000\010\004" +
    "\035\013\246\014\023\001\002\000\010\004\uffec\013\uffec" +
    "\014\uffec\001\002\000\010\004\uffed\013\uffed\014\uffed\001" +
    "\002\000\030\002\uffee\004\uffee\012\uffee\014\uffee\016\uffee" +
    "\043\uffee\045\uffee\046\uffee\047\uffee\050\uffee\053\uffee\001" +
    "\002\000\004\053\250\001\002\000\004\020\251\001\002" +
    "\000\004\006\252\001\002\000\032\002\uffd0\004\uffd0\012" +
    "\uffd0\013\uffd0\014\uffd0\016\uffd0\043\uffd0\045\uffd0\046\uffd0" +
    "\047\uffd0\050\uffd0\053\uffd0\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\250\000\042\002\020\003\025\004\007\005\033\006" +
    "\014\010\031\011\003\012\011\021\017\022\030\023\023" +
    "\024\027\025\005\026\013\027\026\030\021\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\024\023\067\031\230\032\066\033\065\034\074" +
    "\035\075\036\062\037\071\040\076\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\014\174\001\001\000\002\001\001\000\002\001\001" +
    "\000\036\004\156\005\033\006\014\010\031\011\003\012" +
    "\011\021\017\022\030\023\023\024\027\025\005\026\013" +
    "\027\026\030\021\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\007\153" +
    "\001\001\000\002\001\001\000\004\014\037\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\015" +
    "\044\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\014" +
    "\052\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\024\023" +
    "\067\031\077\032\066\033\065\034\074\035\075\036\062" +
    "\037\071\040\076\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\023\067\037\104\040\076" +
    "\001\001\000\024\023\067\031\102\032\066\033\065\034" +
    "\074\035\075\036\062\037\071\040\076\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\023\067\036\115\037\071\040\076\001\001" +
    "\000\012\023\067\036\110\037\071\040\076\001\001\000" +
    "\002\001\001\000\010\023\067\037\114\040\076\001\001" +
    "\000\010\023\067\037\113\040\076\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\023\067" +
    "\035\123\036\062\037\071\040\076\001\001\000\014\023" +
    "\067\035\122\036\062\037\071\040\076\001\001\000\014" +
    "\023\067\035\121\036\062\037\071\040\076\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\030" +
    "\023\067\031\125\032\066\033\065\034\074\035\075\036" +
    "\062\037\071\040\076\041\126\042\127\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\024\023" +
    "\067\031\131\032\066\033\065\034\074\035\075\036\062" +
    "\037\071\040\076\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\024\023\067\031\135\032\066" +
    "\033\065\034\074\035\075\036\062\037\071\040\076\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\030\023\067\031\125\032\066\033\065\034\074\035" +
    "\075\036\062\037\071\040\076\041\141\042\127\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\023\067\033" +
    "\144\034\074\035\075\036\062\037\071\040\076\001\001" +
    "\000\002\001\001\000\016\023\067\034\146\035\075\036" +
    "\062\037\071\040\076\001\001\000\002\001\001\000\002" +
    "\001\001\000\030\023\067\031\125\032\066\033\065\034" +
    "\074\035\075\036\062\037\071\040\076\041\151\042\127" +
    "\001\001\000\002\001\001\000\002\001\001\000\030\005" +
    "\155\006\014\010\031\021\017\022\030\023\023\024\027" +
    "\025\005\026\013\027\026\030\021\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\024\023\067" +
    "\031\160\032\066\033\065\034\074\035\075\036\062\037" +
    "\071\040\076\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\024\023\067\031" +
    "\165\032\066\033\065\034\074\035\075\036\062\037\071" +
    "\040\076\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\030\023\067\031\125\032\066\033\065" +
    "\034\074\035\075\036\062\037\071\040\076\041\171\042" +
    "\127\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\016\202\017\201\020\203\001\001\000\004" +
    "\014\210\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\006\205\001\001\000\002\001\001" +
    "\000\004\020\207\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\030\023\067\031" +
    "\125\032\066\033\065\034\074\035\075\036\062\037\071" +
    "\040\076\041\217\042\127\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\024\023\067\031\223" +
    "\032\066\033\065\034\074\035\075\036\062\037\071\040" +
    "\076\001\001\000\002\001\001\000\004\006\225\001\001" +
    "\000\002\001\001\000\004\006\227\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\024\023\067\031\234\032\066\033\065\034\074\035" +
    "\075\036\062\037\071\040\076\001\001\000\002\001\001" +
    "\000\004\006\236\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\013\242\001\001\000\006" +
    "\010\244\011\243\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ConstructorAST$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ConstructorAST$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ConstructorAST$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

   errores = new GestionErrores();
   AnalizadorLexico alex = (AnalizadorLexico) getScanner();
   alex.fijaGestionErrores(errores);

    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return getScanner().next_token(); 
    }


   private GestionErrores errores;

   public void syntax_error(Symbol unidadLexica) {
      errores.errorSintactico((UnidadLexica) unidadLexica);
   }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ConstructorAST$actions {
  private final ConstructorAST parser;

  /** Constructor */
  CUP$ConstructorAST$actions(ConstructorAST parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ConstructorAST$do_action_part00000000(
    int                        CUP$ConstructorAST$act_num,
    java_cup.runtime.lr_parser CUP$ConstructorAST$parser,
    java.util.Stack            CUP$ConstructorAST$stack,
    int                        CUP$ConstructorAST$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ConstructorAST$result;

      /* select the action based on the action number */
      switch (CUP$ConstructorAST$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		Programa start_val = (Programa)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		RESULT = start_val;
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP$ConstructorAST$parser.done_parsing();
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= lista_inst 
            {
              Programa RESULT =null;
		List<I> li = (List<I>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Programa(li); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("programa",0, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_inst ::= lista_inst inst 
            {
              List<I> RESULT =null;
		List<I> li = (List<I>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		I i = (I)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 li.add(i); RESULT = li; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_inst",1, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_inst ::= inst 
            {
              List<I> RESULT =null;
		I i = (I)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 
                  List<I> l = new ArrayList<I>();
                  l.add(i);
                  RESULT = l;
               
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_inst",1, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // inst ::= declaracion_funcion 
            {
              I RESULT =null;
		DecFuncion f = (DecFuncion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = f; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("inst",2, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // inst ::= declaracion_clase 
            {
              I RESULT =null;
		DecClase c = (DecClase)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = c; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("inst",2, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // inst ::= stmt 
            {
              I RESULT =null;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = s; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("inst",2, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // stmt ::= declaracion_variable 
            {
              Stmt RESULT =null;
		DecVar d = (DecVar)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = d; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // stmt ::= if_stmt 
            {
              Stmt RESULT =null;
		If i = (If)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = i; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // stmt ::= while_stmt 
            {
              Stmt RESULT =null;
		While w = (While)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = w; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= read_stmt 
            {
              Stmt RESULT =null;
		Read r = (Read)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = r; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= print_stmt 
            {
              Stmt RESULT =null;
		Print p = (Print)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = p; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmt ::= bloque 
            {
              Stmt RESULT =null;
		Bloque b = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = b; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // stmt ::= asignacion 
            {
              Stmt RESULT =null;
		Asignacion a = (Asignacion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = a; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // stmt ::= llamada_stmt 
            {
              Stmt RESULT =null;
		LlamadaStmt c = (LlamadaStmt)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = c; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // stmt ::= return_stmt 
            {
              Stmt RESULT =null;
		Return r = (Return)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = r; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // declaracion_variable ::= VAR tipo DOS_PUNTOS ID PUNTO_Y_COMA 
            {
              DecVar RESULT =null;
		T t = (T)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new DecVar(t, id.lexema, null); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("declaracion_variable",6, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // declaracion_variable ::= VAR tipo DOS_PUNTOS ID IGUAL expr PUNTO_Y_COMA 
            {
              DecVar RESULT =null;
		T t = (T)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-5)).value;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new DecVar(t, id.lexema, e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("declaracion_variable",6, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // declaracion_funcion ::= FUNC tipo DOS_PUNTOS ID PARENTESIS_APERTURA params_opt PARENTESIS_CIERRE bloque 
            {
              DecFuncion RESULT =null;
		T t = (T)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-6)).value;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-4)).value;
		List<Parametro> ps = (List<Parametro>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		Bloque b = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new DecFuncion(t, id.lexema, ps, b); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("declaracion_funcion",7, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declaracion_clase ::= CLASS DOS_PUNTOS ID LLAVE_APERTURA lista_miembros LLAVE_CIERRE 
            {
              DecClase RESULT =null;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		List<I> lm = (List<I>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		
                         java.util.List<DecVar> campos = new ArrayList<DecVar>();
                         java.util.List<DecFuncion> metodos = new ArrayList<DecFuncion>();
                         for (I m : lm) {
                            if (m instanceof DecVar) campos.add((DecVar) m);
                            else if (m instanceof DecFuncion) metodos.add((DecFuncion) m);
                         }
                         RESULT = new DecClase(id.lexema, campos, metodos);
                      
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("declaracion_clase",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // lista_miembros ::= lista_miembros declaracion_variable 
            {
              List<I> RESULT =null;
		List<I> lm = (List<I>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		DecVar d = (DecVar)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 lm.add(d); RESULT = lm; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_miembros",9, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // lista_miembros ::= lista_miembros declaracion_funcion 
            {
              List<I> RESULT =null;
		List<I> lm = (List<I>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		DecFuncion f = (DecFuncion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 lm.add(f); RESULT = lm; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_miembros",9, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // lista_miembros ::= 
            {
              List<I> RESULT =null;
		 RESULT = new ArrayList<I>(); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_miembros",9, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipo ::= INT 
            {
              T RESULT =null;
		 RESULT = new TipoBasico("int"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("tipo",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo ::= REAL 
            {
              T RESULT =null;
		 RESULT = new TipoBasico("real"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("tipo",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo ::= BOOL 
            {
              T RESULT =null;
		 RESULT = new TipoBasico("bool"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("tipo",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipo ::= VOID 
            {
              T RESULT =null;
		 RESULT = new TipoBasico("void"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("tipo",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // tipo ::= ARRAY dimensiones OF tipo 
            {
              T RESULT =null;
		List<Integer> ds = (List<Integer>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		T t = (T)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new TipoArray(ds, t); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("tipo",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // tipo ::= ID 
            {
              T RESULT =null;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new TipoClase(id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("tipo",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // dimensiones ::= dimensiones CORCHETE_APERTURA NUM CORCHETE_CIERRE 
            {
              List<Integer> RESULT =null;
		List<Integer> ds = (List<Integer>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		alex.TokenValue n = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 ds.add(Integer.parseInt(n.lexema)); RESULT = ds; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("dimensiones",11, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // dimensiones ::= CORCHETE_APERTURA NUM CORCHETE_CIERRE 
            {
              List<Integer> RESULT =null;
		alex.TokenValue n = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		
                   List<Integer> l = new ArrayList<Integer>();
                   l.add(Integer.parseInt(n.lexema));
                   RESULT = l;
                 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("dimensiones",11, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // params_opt ::= lista_params 
            {
              List<Parametro> RESULT =null;
		List<Parametro> lp = (List<Parametro>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = lp; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("params_opt",12, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // params_opt ::= 
            {
              List<Parametro> RESULT =null;
		 RESULT = new ArrayList<Parametro>(); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("params_opt",12, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // lista_params ::= lista_params COMA param 
            {
              List<Parametro> RESULT =null;
		List<Parametro> lp = (List<Parametro>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		Parametro p = (Parametro)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 lp.add(p); RESULT = lp; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_params",13, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // lista_params ::= param 
            {
              List<Parametro> RESULT =null;
		Parametro p = (Parametro)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		
                    List<Parametro> l = new ArrayList<Parametro>();
                    l.add(p);
                    RESULT = l;
                  
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_params",13, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // param ::= VAR tipo DOS_PUNTOS ID 
            {
              Parametro RESULT =null;
		T t = (T)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Parametro(t, id.lexema, false); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("param",14, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // param ::= VAR tipo DOS_PUNTOS AMPERSAND ID 
            {
              Parametro RESULT =null;
		T t = (T)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Parametro(t, id.lexema, true); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("param",14, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // bloque ::= LLAVE_APERTURA lista_stmt LLAVE_CIERRE 
            {
              Bloque RESULT =null;
		List<Stmt> ls = (List<Stmt>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Bloque(ls); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("bloque",4, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // lista_stmt ::= lista_stmt stmt 
            {
              List<Stmt> RESULT =null;
		List<Stmt> ls = (List<Stmt>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 ls.add(s); RESULT = ls; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_stmt",5, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // lista_stmt ::= 
            {
              List<Stmt> RESULT =null;
		 RESULT = new ArrayList<Stmt>(); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_stmt",5, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // asignacion ::= lhs IGUAL expr PUNTO_Y_COMA 
            {
              Asignacion RESULT =null;
		E l = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Asignacion(l, e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("asignacion",15, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // llamada_stmt ::= ID PARENTESIS_APERTURA args_opt PARENTESIS_CIERRE PUNTO_Y_COMA 
            {
              LlamadaStmt RESULT =null;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-4)).value;
		List<E> as = (List<E>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		 RESULT = new LlamadaStmt(new LlamadaFuncion(id.lexema, as)); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("llamada_stmt",16, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // llamada_stmt ::= lhs PUNTO ID PARENTESIS_APERTURA args_opt PARENTESIS_CIERRE PUNTO_Y_COMA 
            {
              LlamadaStmt RESULT =null;
		E l = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-6)).value;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-4)).value;
		List<E> as = (List<E>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		 RESULT = new LlamadaStmt(new LlamadaMetodo(l, id.lexema, as)); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("llamada_stmt",16, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // lhs ::= ID 
            {
              E RESULT =null;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Id(id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lhs",17, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // lhs ::= lhs CORCHETE_APERTURA expr CORCHETE_CIERRE 
            {
              E RESULT =null;
		E l = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new AccesoArray(l, e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lhs",17, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // lhs ::= lhs PUNTO ID 
            {
              E RESULT =null;
		E l = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new AccesoCampo(l, id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lhs",17, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // if_stmt ::= IF PARENTESIS_APERTURA expr PARENTESIS_CIERRE bloque 
            {
              If RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		Bloque b = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new If(e, b, null); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("if_stmt",18, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // if_stmt ::= IF PARENTESIS_APERTURA expr PARENTESIS_CIERRE bloque ELSE bloque 
            {
              If RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-4)).value;
		Bloque b1 = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		Bloque b2 = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new If(e, b1, b2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("if_stmt",18, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // while_stmt ::= WHILE PARENTESIS_APERTURA expr PARENTESIS_CIERRE bloque 
            {
              While RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		Bloque b = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new While(e, b); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("while_stmt",19, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // read_stmt ::= READ PARENTESIS_APERTURA ID PARENTESIS_CIERRE PUNTO_Y_COMA 
            {
              Read RESULT =null;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		 RESULT = new Read(id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("read_stmt",20, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // print_stmt ::= PRINT PARENTESIS_APERTURA expr PARENTESIS_CIERRE PUNTO_Y_COMA 
            {
              Print RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		 RESULT = new Print(e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("print_stmt",21, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // return_stmt ::= RETURN expr PUNTO_Y_COMA 
            {
              Return RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Return(e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("return_stmt",22, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // return_stmt ::= RETURN PUNTO_Y_COMA 
            {
              Return RESULT =null;
		 RESULT = new Return(null); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("return_stmt",22, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= expr_or 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr",23, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr_or ::= expr_or OR expr_and 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.OR, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_or",24, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr_or ::= expr_and 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_or",24, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr_and ::= expr_and AND expr_rel 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.AND, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_and",25, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr_and ::= expr_rel 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_and",25, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr_rel ::= expr_rel MENOR expr_add 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.MENOR, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_rel",26, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr_rel ::= expr_rel MAYOR expr_add 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.MAYOR, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_rel",26, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr_rel ::= expr_rel IGUALDAD expr_add 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.IGUALDAD, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_rel",26, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr_rel ::= expr_add 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_rel",26, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr_add ::= expr_add SUMA expr_mul 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.SUMA, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_add",27, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr_add ::= expr_add RESTA expr_mul 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.RESTA, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_add",27, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr_add ::= expr_mul 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_add",27, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr_mul ::= expr_mul MULTIPLICACION expr_unaria 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.MUL, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_mul",28, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr_mul ::= expr_mul DIVISION expr_unaria 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.DIV, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_mul",28, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expr_mul ::= expr_unaria 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_mul",28, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expr_unaria ::= RESTA expr_unaria 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpUnaria(KindE.MENOS_UNARIO, e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_unaria",29, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expr_unaria ::= expr_base 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_unaria",29, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expr_base ::= NUM 
            {
              E RESULT =null;
		alex.TokenValue n = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Num(n.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",30, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expr_base ::= NUM_REAL 
            {
              E RESULT =null;
		alex.TokenValue n = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new NumReal(n.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",30, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expr_base ::= TRUE 
            {
              E RESULT =null;
		 RESULT = new Bool(true); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",30, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expr_base ::= FALSE 
            {
              E RESULT =null;
		 RESULT = new Bool(false); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",30, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // expr_base ::= lhs 
            {
              E RESULT =null;
		E l = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = l; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",30, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // expr_base ::= ID PARENTESIS_APERTURA args_opt PARENTESIS_CIERRE 
            {
              E RESULT =null;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		List<E> as = (List<E>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new LlamadaFuncion(id.lexema, as); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",30, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // expr_base ::= lhs PUNTO ID PARENTESIS_APERTURA args_opt PARENTESIS_CIERRE 
            {
              E RESULT =null;
		E l = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-5)).value;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		List<E> as = (List<E>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new LlamadaMetodo(l, id.lexema, as); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",30, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // expr_base ::= NEW ID PARENTESIS_APERTURA args_opt PARENTESIS_CIERRE 
            {
              E RESULT =null;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		List<E> as = (List<E>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new NewInstancia(id.lexema, as); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",30, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // expr_base ::= PARENTESIS_APERTURA expr PARENTESIS_CIERRE 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",30, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // args_opt ::= lista_args 
            {
              List<E> RESULT =null;
		List<E> la = (List<E>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = la; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("args_opt",31, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // args_opt ::= 
            {
              List<E> RESULT =null;
		 RESULT = new ArrayList<E>(); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("args_opt",31, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // lista_args ::= lista_args COMA expr 
            {
              List<E> RESULT =null;
		List<E> la = (List<E>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 la.add(e); RESULT = la; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_args",32, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // lista_args ::= expr 
            {
              List<E> RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		
                  List<E> l = new ArrayList<E>();
                  l.add(e);
                  RESULT = l;
                
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_args",32, RESULT);
            }
          return CUP$ConstructorAST$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ConstructorAST$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ConstructorAST$do_action(
    int                        CUP$ConstructorAST$act_num,
    java_cup.runtime.lr_parser CUP$ConstructorAST$parser,
    java.util.Stack            CUP$ConstructorAST$stack,
    int                        CUP$ConstructorAST$top)
    throws java.lang.Exception
    {
              return CUP$ConstructorAST$do_action_part00000000(
                               CUP$ConstructorAST$act_num,
                               CUP$ConstructorAST$parser,
                               CUP$ConstructorAST$stack,
                               CUP$ConstructorAST$top);
    }
}

