
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue May 05 13:10:38 CEST 2026
//----------------------------------------------------

package constructorast;

import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.List;
import alex.AnalizadorLexico;
import alex.UnidadLexica;
import errors.GestionErrores;
import ast.*;
import java_cup.runtime.ComplexSymbolFactory.Location;

/** CUP v0.11b beta 20140220 generated parser.
  * @version Tue May 05 13:10:38 CEST 2026
  */
public class ConstructorAST extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ConstructorAST() {super();}

  /** Constructor which sets the default scanner. */
  public ConstructorAST(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ConstructorAST(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\107\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\003\000\002\010\007\000\002\010" +
    "\011\000\002\011\012\000\002\012\003\000\002\012\003" +
    "\000\002\012\003\000\002\012\003\000\002\012\006\000" +
    "\002\013\006\000\002\013\005\000\002\014\003\000\002" +
    "\014\002\000\002\015\005\000\002\015\003\000\002\016" +
    "\006\000\002\016\007\000\002\006\005\000\002\007\004" +
    "\000\002\007\002\000\002\017\006\000\002\020\003\000" +
    "\002\020\006\000\002\021\007\000\002\021\011\000\002" +
    "\022\007\000\002\023\007\000\002\024\007\000\002\025" +
    "\005\000\002\025\004\000\002\026\003\000\002\027\005" +
    "\000\002\027\003\000\002\030\005\000\002\030\003\000" +
    "\002\031\005\000\002\031\005\000\002\031\005\000\002" +
    "\031\003\000\002\032\005\000\002\032\005\000\002\032" +
    "\003\000\002\033\005\000\002\033\005\000\002\033\003" +
    "\000\002\034\004\000\002\034\003\000\002\035\003\000" +
    "\002\035\003\000\002\035\003\000\002\035\003\000\002" +
    "\035\003\000\002\035\006\000\002\035\005\000\002\036" +
    "\003\000\002\036\002\000\002\037\005\000\002\037\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\211\000\024\004\032\012\030\014\021\016\012\043" +
    "\014\045\010\046\005\047\023\050\016\001\002\000\026" +
    "\002\ufffd\004\ufffd\012\ufffd\014\ufffd\016\ufffd\043\ufffd\045" +
    "\ufffd\046\ufffd\047\ufffd\050\ufffd\001\002\000\004\017\210" +
    "\001\002\000\030\002\ufff9\004\ufff9\012\ufff9\013\ufff9\014" +
    "\ufff9\016\ufff9\043\ufff9\045\ufff9\046\ufff9\047\ufff9\050\ufff9" +
    "\001\002\000\026\002\ufffe\004\ufffe\012\ufffe\014\ufffe\016" +
    "\ufffe\043\ufffe\045\ufffe\046\ufffe\047\ufffe\050\ufffe\001\002" +
    "\000\004\017\204\001\002\000\030\002\ufff8\004\ufff8\012" +
    "\ufff8\013\ufff8\014\ufff8\016\ufff8\043\ufff8\045\ufff8\046\ufff8" +
    "\047\ufff8\050\ufff8\001\002\000\022\006\201\017\075\030" +
    "\064\031\066\033\074\050\067\051\057\052\060\001\002" +
    "\000\030\002\ufff6\004\ufff6\012\ufff6\013\ufff6\014\ufff6\016" +
    "\ufff6\043\ufff6\045\ufff6\046\ufff6\047\ufff6\050\ufff6\001\002" +
    "\000\004\017\173\001\002\000\030\002\ufff5\004\ufff5\012" +
    "\ufff5\013\ufff5\014\ufff5\016\ufff5\043\ufff5\045\ufff5\046\ufff5" +
    "\047\ufff5\050\ufff5\001\002\000\006\007\uffdf\021\uffdf\001" +
    "\002\000\004\002\172\001\002\000\030\002\ufff4\004\ufff4" +
    "\012\ufff4\013\ufff4\014\ufff4\016\ufff4\043\ufff4\045\ufff4\046" +
    "\ufff4\047\ufff4\050\ufff4\001\002\000\014\010\040\015\036" +
    "\025\037\026\034\027\035\001\002\000\006\007\146\021" +
    "\127\001\002\000\004\017\142\001\002\000\026\002\000" +
    "\004\032\012\030\014\021\016\012\043\014\045\010\046" +
    "\005\047\023\050\016\001\002\000\030\002\ufffa\004\ufffa" +
    "\012\ufffa\013\ufffa\014\ufffa\016\ufffa\043\ufffa\045\ufffa\046" +
    "\ufffa\047\ufffa\050\ufffa\001\002\000\030\002\ufff7\004\ufff7" +
    "\012\ufff7\013\ufff7\014\ufff7\016\ufff7\043\ufff7\045\ufff7\046" +
    "\ufff7\047\ufff7\050\ufff7\001\002\000\030\002\ufffb\004\ufffb" +
    "\012\ufffb\013\ufffb\014\ufffb\016\ufffb\043\ufffb\045\ufffb\046" +
    "\ufffb\047\ufffb\050\ufffb\001\002\000\024\004\uffe1\012\uffe1" +
    "\013\uffe1\016\uffe1\043\uffe1\045\uffe1\046\uffe1\047\uffe1\050" +
    "\uffe1\001\002\000\026\002\ufffc\004\ufffc\012\ufffc\014\ufffc" +
    "\016\ufffc\043\ufffc\045\ufffc\046\ufffc\047\ufffc\050\ufffc\001" +
    "\002\000\014\010\040\015\036\025\037\026\034\027\035" +
    "\001\002\000\004\005\052\001\002\000\004\005\uffef\001" +
    "\002\000\004\005\uffee\001\002\000\004\005\uffed\001\002" +
    "\000\004\005\ufff0\001\002\000\004\021\041\001\002\000" +
    "\004\051\050\001\002\000\006\011\044\021\043\001\002" +
    "\000\004\051\046\001\002\000\014\010\040\015\036\025" +
    "\037\026\034\027\035\001\002\000\004\005\uffec\001\002" +
    "\000\004\022\047\001\002\000\006\011\uffeb\021\uffeb\001" +
    "\002\000\004\022\051\001\002\000\006\011\uffea\021\uffea" +
    "\001\002\000\004\050\053\001\002\000\006\006\055\007" +
    "\054\001\002\000\020\017\075\030\064\031\066\033\074" +
    "\050\067\051\057\052\060\001\002\000\030\002\ufff3\004" +
    "\ufff3\012\ufff3\013\ufff3\014\ufff3\016\ufff3\043\ufff3\045\ufff3" +
    "\046\ufff3\047\ufff3\050\ufff3\001\002\000\034\006\uffcb\020" +
    "\uffcb\022\uffcb\023\uffcb\032\uffcb\033\uffcb\034\105\035\106" +
    "\036\uffcb\037\uffcb\040\uffcb\041\uffcb\042\uffcb\001\002\000" +
    "\034\006\uffc5\020\uffc5\022\uffc5\023\uffc5\032\uffc5\033\uffc5" +
    "\034\uffc5\035\uffc5\036\uffc5\037\uffc5\040\uffc5\041\uffc5\042" +
    "\uffc5\001\002\000\034\006\uffc4\020\uffc4\022\uffc4\023\uffc4" +
    "\032\uffc4\033\uffc4\034\uffc4\035\uffc4\036\uffc4\037\uffc4\040" +
    "\uffc4\041\uffc4\042\uffc4\001\002\000\016\006\uffd4\020\uffd4" +
    "\022\uffd4\023\uffd4\041\134\042\uffd4\001\002\000\014\006" +
    "\uffd6\020\uffd6\022\uffd6\023\uffd6\042\132\001\002\000\036" +
    "\006\uffc1\020\uffc1\021\127\022\uffc1\023\uffc1\032\uffc1\033" +
    "\uffc1\034\uffc1\035\uffc1\036\uffc1\037\uffc1\040\uffc1\041\uffc1" +
    "\042\uffc1\001\002\000\034\006\uffc3\020\uffc3\022\uffc3\023" +
    "\uffc3\032\uffc3\033\uffc3\034\uffc3\035\uffc3\036\uffc3\037\uffc3" +
    "\040\uffc3\041\uffc3\042\uffc3\001\002\000\034\006\uffc8\020" +
    "\uffc8\022\uffc8\023\uffc8\032\uffc8\033\uffc8\034\uffc8\035\uffc8" +
    "\036\uffc8\037\uffc8\040\uffc8\041\uffc8\042\uffc8\001\002\000" +
    "\034\006\uffc2\020\uffc2\022\uffc2\023\uffc2\032\uffc2\033\uffc2" +
    "\034\uffc2\035\uffc2\036\uffc2\037\uffc2\040\uffc2\041\uffc2\042" +
    "\uffc2\001\002\000\040\006\uffdf\017\120\020\uffdf\021\uffdf" +
    "\022\uffdf\023\uffdf\032\uffdf\033\uffdf\034\uffdf\035\uffdf\036" +
    "\uffdf\037\uffdf\040\uffdf\041\uffdf\042\uffdf\001\002\000\024" +
    "\006\uffd2\020\uffd2\022\uffd2\023\uffd2\036\113\037\114\040" +
    "\112\041\uffd2\042\uffd2\001\002\000\030\006\uffce\020\uffce" +
    "\022\uffce\023\uffce\032\103\033\102\036\uffce\037\uffce\040" +
    "\uffce\041\uffce\042\uffce\001\002\000\004\006\101\001\002" +
    "\000\034\006\uffc6\020\uffc6\022\uffc6\023\uffc6\032\uffc6\033" +
    "\uffc6\034\uffc6\035\uffc6\036\uffc6\037\uffc6\040\uffc6\041\uffc6" +
    "\042\uffc6\001\002\000\020\017\075\030\064\031\066\033" +
    "\074\050\067\051\057\052\060\001\002\000\020\017\075" +
    "\030\064\031\066\033\074\050\067\051\057\052\060\001" +
    "\002\000\004\020\077\001\002\000\034\006\uffbf\020\uffbf" +
    "\022\uffbf\023\uffbf\032\uffbf\033\uffbf\034\uffbf\035\uffbf\036" +
    "\uffbf\037\uffbf\040\uffbf\041\uffbf\042\uffbf\001\002\000\034" +
    "\006\uffc7\020\uffc7\022\uffc7\023\uffc7\032\uffc7\033\uffc7\034" +
    "\uffc7\035\uffc7\036\uffc7\037\uffc7\040\uffc7\041\uffc7\042\uffc7" +
    "\001\002\000\030\002\ufff2\004\ufff2\012\ufff2\013\ufff2\014" +
    "\ufff2\016\ufff2\043\ufff2\045\ufff2\046\ufff2\047\ufff2\050\ufff2" +
    "\001\002\000\020\017\075\030\064\031\066\033\074\050" +
    "\067\051\057\052\060\001\002\000\020\017\075\030\064" +
    "\031\066\033\074\050\067\051\057\052\060\001\002\000" +
    "\034\006\uffcd\020\uffcd\022\uffcd\023\uffcd\032\uffcd\033\uffcd" +
    "\034\105\035\106\036\uffcd\037\uffcd\040\uffcd\041\uffcd\042" +
    "\uffcd\001\002\000\020\017\075\030\064\031\066\033\074" +
    "\050\067\051\057\052\060\001\002\000\020\017\075\030" +
    "\064\031\066\033\074\050\067\051\057\052\060\001\002" +
    "\000\034\006\uffc9\020\uffc9\022\uffc9\023\uffc9\032\uffc9\033" +
    "\uffc9\034\uffc9\035\uffc9\036\uffc9\037\uffc9\040\uffc9\041\uffc9" +
    "\042\uffc9\001\002\000\034\006\uffca\020\uffca\022\uffca\023" +
    "\uffca\032\uffca\033\uffca\034\uffca\035\uffca\036\uffca\037\uffca" +
    "\040\uffca\041\uffca\042\uffca\001\002\000\034\006\uffcc\020" +
    "\uffcc\022\uffcc\023\uffcc\032\uffcc\033\uffcc\034\105\035\106" +
    "\036\uffcc\037\uffcc\040\uffcc\041\uffcc\042\uffcc\001\002\000" +
    "\020\017\075\030\064\031\066\033\074\050\067\051\057" +
    "\052\060\001\002\000\020\017\075\030\064\031\066\033" +
    "\074\050\067\051\057\052\060\001\002\000\020\017\075" +
    "\030\064\031\066\033\074\050\067\051\057\052\060\001" +
    "\002\000\030\006\uffd0\020\uffd0\022\uffd0\023\uffd0\032\103" +
    "\033\102\036\uffd0\037\uffd0\040\uffd0\041\uffd0\042\uffd0\001" +
    "\002\000\030\006\uffd1\020\uffd1\022\uffd1\023\uffd1\032\103" +
    "\033\102\036\uffd1\037\uffd1\040\uffd1\041\uffd1\042\uffd1\001" +
    "\002\000\030\006\uffcf\020\uffcf\022\uffcf\023\uffcf\032\103" +
    "\033\102\036\uffcf\037\uffcf\040\uffcf\041\uffcf\042\uffcf\001" +
    "\002\000\022\017\075\020\uffbd\030\064\031\066\033\074" +
    "\050\067\051\057\052\060\001\002\000\006\020\uffbb\023" +
    "\uffbb\001\002\000\004\020\126\001\002\000\006\020\uffbe" +
    "\023\124\001\002\000\020\017\075\030\064\031\066\033" +
    "\074\050\067\051\057\052\060\001\002\000\006\020\uffbc" +
    "\023\uffbc\001\002\000\034\006\uffc0\020\uffc0\022\uffc0\023" +
    "\uffc0\032\uffc0\033\uffc0\034\uffc0\035\uffc0\036\uffc0\037\uffc0" +
    "\040\uffc0\041\uffc0\042\uffc0\001\002\000\020\017\075\030" +
    "\064\031\066\033\074\050\067\051\057\052\060\001\002" +
    "\000\004\022\131\001\002\000\040\006\uffde\007\uffde\020" +
    "\uffde\021\uffde\022\uffde\023\uffde\032\uffde\033\uffde\034\uffde" +
    "\035\uffde\036\uffde\037\uffde\040\uffde\041\uffde\042\uffde\001" +
    "\002\000\020\017\075\030\064\031\066\033\074\050\067" +
    "\051\057\052\060\001\002\000\016\006\uffd5\020\uffd5\022" +
    "\uffd5\023\uffd5\041\134\042\uffd5\001\002\000\020\017\075" +
    "\030\064\031\066\033\074\050\067\051\057\052\060\001" +
    "\002\000\024\006\uffd3\020\uffd3\022\uffd3\023\uffd3\036\113" +
    "\037\114\040\112\041\uffd3\042\uffd3\001\002\000\024\004" +
    "\032\012\030\013\137\016\012\043\014\045\010\046\005" +
    "\047\023\050\016\001\002\000\032\002\uffe3\004\uffe3\012" +
    "\uffe3\013\uffe3\014\uffe3\016\uffe3\043\uffe3\044\uffe3\045\uffe3" +
    "\046\uffe3\047\uffe3\050\uffe3\001\002\000\024\004\uffe2\012" +
    "\uffe2\013\uffe2\016\uffe2\043\uffe2\045\uffe2\046\uffe2\047\uffe2" +
    "\050\uffe2\001\002\000\026\002\uffff\004\uffff\012\uffff\014" +
    "\uffff\016\uffff\043\uffff\045\uffff\046\uffff\047\uffff\050\uffff" +
    "\001\002\000\020\017\075\030\064\031\066\033\074\050" +
    "\067\051\057\052\060\001\002\000\004\020\144\001\002" +
    "\000\004\006\145\001\002\000\030\002\uffd9\004\uffd9\012" +
    "\uffd9\013\uffd9\014\uffd9\016\uffd9\043\uffd9\045\uffd9\046\uffd9" +
    "\047\uffd9\050\uffd9\001\002\000\020\017\075\030\064\031" +
    "\066\033\074\050\067\051\057\052\060\001\002\000\004" +
    "\006\150\001\002\000\030\002\uffe0\004\uffe0\012\uffe0\013" +
    "\uffe0\014\uffe0\016\uffe0\043\uffe0\045\uffe0\046\uffe0\047\uffe0" +
    "\050\uffe0\001\002\000\004\005\152\001\002\000\004\050" +
    "\153\001\002\000\004\017\154\001\002\000\006\004\155" +
    "\020\uffe8\001\002\000\014\010\040\015\036\025\037\026" +
    "\034\027\035\001\002\000\006\020\uffe9\023\163\001\002" +
    "\000\004\020\161\001\002\000\006\020\uffe6\023\uffe6\001" +
    "\002\000\004\012\030\001\002\000\026\002\ufff1\004\ufff1" +
    "\012\ufff1\014\ufff1\016\ufff1\043\ufff1\045\ufff1\046\ufff1\047" +
    "\ufff1\050\ufff1\001\002\000\004\004\155\001\002\000\006" +
    "\020\uffe7\023\uffe7\001\002\000\004\005\166\001\002\000" +
    "\006\024\170\050\167\001\002\000\006\020\uffe5\023\uffe5" +
    "\001\002\000\004\050\171\001\002\000\006\020\uffe4\023" +
    "\uffe4\001\002\000\004\002\001\001\002\000\020\017\075" +
    "\030\064\031\066\033\074\050\067\051\057\052\060\001" +
    "\002\000\004\020\175\001\002\000\004\012\030\001\002" +
    "\000\032\002\uffdd\004\uffdd\012\uffdd\013\uffdd\014\uffdd\016" +
    "\uffdd\043\uffdd\044\177\045\uffdd\046\uffdd\047\uffdd\050\uffdd" +
    "\001\002\000\004\012\030\001\002\000\030\002\uffdc\004" +
    "\uffdc\012\uffdc\013\uffdc\014\uffdc\016\uffdc\043\uffdc\045\uffdc" +
    "\046\uffdc\047\uffdc\050\uffdc\001\002\000\030\002\uffd7\004" +
    "\uffd7\012\uffd7\013\uffd7\014\uffd7\016\uffd7\043\uffd7\045\uffd7" +
    "\046\uffd7\047\uffd7\050\uffd7\001\002\000\004\006\203\001" +
    "\002\000\030\002\uffd8\004\uffd8\012\uffd8\013\uffd8\014\uffd8" +
    "\016\uffd8\043\uffd8\045\uffd8\046\uffd8\047\uffd8\050\uffd8\001" +
    "\002\000\020\017\075\030\064\031\066\033\074\050\067" +
    "\051\057\052\060\001\002\000\004\020\206\001\002\000" +
    "\004\012\030\001\002\000\030\002\uffdb\004\uffdb\012\uffdb" +
    "\013\uffdb\014\uffdb\016\uffdb\043\uffdb\045\uffdb\046\uffdb\047" +
    "\uffdb\050\uffdb\001\002\000\004\050\211\001\002\000\004" +
    "\020\212\001\002\000\004\006\213\001\002\000\030\002" +
    "\uffda\004\uffda\012\uffda\013\uffda\014\uffda\016\uffda\043\uffda" +
    "\045\uffda\046\uffda\047\uffda\050\uffda\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\211\000\036\002\016\003\023\004\006\005\030\006" +
    "\012\010\026\011\003\017\014\020\021\021\024\022\005" +
    "\023\010\024\025\025\017\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\024\020\062\026\201\027" +
    "\061\030\060\031\067\032\070\033\055\034\064\035\072" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\012\150\001\001\000\002\001\001\000\002\001" +
    "\001\000\032\004\140\005\030\006\012\010\026\011\003" +
    "\017\014\020\021\021\024\022\005\023\010\024\025\025" +
    "\017\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\135\001\001\000\002\001\001\000" +
    "\004\012\032\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\013\041\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\012\044\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\024\020\062\026\071\027\061\030\060\031\067\032\070" +
    "\033\055\034\064\035\072\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\020\062\034\077\035\072\001\001" +
    "\000\024\020\062\026\075\027\061\030\060\031\067\032" +
    "\070\033\055\034\064\035\072\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\020\062\033\110\034\064\035\072\001\001\000\012" +
    "\020\062\033\103\034\064\035\072\001\001\000\002\001" +
    "\001\000\010\020\062\034\107\035\072\001\001\000\010" +
    "\020\062\034\106\035\072\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\014\020\062\032\116" +
    "\033\055\034\064\035\072\001\001\000\014\020\062\032" +
    "\115\033\055\034\064\035\072\001\001\000\014\020\062" +
    "\032\114\033\055\034\064\035\072\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\030\020\062" +
    "\026\120\027\061\030\060\031\067\032\070\033\055\034" +
    "\064\035\072\036\121\037\122\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\024\020\062\026" +
    "\124\027\061\030\060\031\067\032\070\033\055\034\064" +
    "\035\072\001\001\000\002\001\001\000\002\001\001\000" +
    "\024\020\062\026\127\027\061\030\060\031\067\032\070" +
    "\033\055\034\064\035\072\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\020\062\030\132\031\067\032\070" +
    "\033\055\034\064\035\072\001\001\000\002\001\001\000" +
    "\016\020\062\031\134\032\070\033\055\034\064\035\072" +
    "\001\001\000\002\001\001\000\026\005\137\006\012\010" +
    "\026\017\014\020\021\021\024\022\005\023\010\024\025" +
    "\025\017\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\024\020\062\026\142\027\061\030\060" +
    "\031\067\032\070\033\055\034\064\035\072\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\024" +
    "\020\062\026\146\027\061\030\060\031\067\032\070\033" +
    "\055\034\064\035\072\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\014\156\015\155\016\157\001\001\000\004" +
    "\012\164\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\006\161\001\001\000\002\001\001" +
    "\000\004\016\163\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\024\020\062\026" +
    "\173\027\061\030\060\031\067\032\070\033\055\034\064" +
    "\035\072\001\001\000\002\001\001\000\004\006\175\001" +
    "\001\000\002\001\001\000\004\006\177\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\024\020\062\026\204\027\061\030\060\031\067" +
    "\032\070\033\055\034\064\035\072\001\001\000\002\001" +
    "\001\000\004\006\206\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ConstructorAST$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ConstructorAST$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ConstructorAST$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

   errores = new GestionErrores();
   AnalizadorLexico alex = (AnalizadorLexico) getScanner();
   alex.fijaGestionErrores(errores);

    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return getScanner().next_token(); 
    }


   private GestionErrores errores;

   public void syntax_error(Symbol unidadLexica) {
      errores.errorSintactico((UnidadLexica) unidadLexica);
   }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ConstructorAST$actions {
  private final ConstructorAST parser;

  /** Constructor */
  CUP$ConstructorAST$actions(ConstructorAST parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ConstructorAST$do_action_part00000000(
    int                        CUP$ConstructorAST$act_num,
    java_cup.runtime.lr_parser CUP$ConstructorAST$parser,
    java.util.Stack            CUP$ConstructorAST$stack,
    int                        CUP$ConstructorAST$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ConstructorAST$result;

      /* select the action based on the action number */
      switch (CUP$ConstructorAST$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		Programa start_val = (Programa)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		RESULT = start_val;
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP$ConstructorAST$parser.done_parsing();
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= lista_inst 
            {
              Programa RESULT =null;
		List<I> li = (List<I>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Programa(li); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("programa",0, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_inst ::= lista_inst inst 
            {
              List<I> RESULT =null;
		List<I> li = (List<I>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		I i = (I)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 li.add(i); RESULT = li; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_inst",1, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_inst ::= inst 
            {
              List<I> RESULT =null;
		I i = (I)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 
                  List<I> l = new ArrayList<I>();
                  l.add(i);
                  RESULT = l;
               
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_inst",1, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // inst ::= declaracion_funcion 
            {
              I RESULT =null;
		DecFuncion f = (DecFuncion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = f; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("inst",2, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // inst ::= stmt 
            {
              I RESULT =null;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = s; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("inst",2, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // stmt ::= declaracion_variable 
            {
              Stmt RESULT =null;
		DecVar d = (DecVar)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = d; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // stmt ::= if_stmt 
            {
              Stmt RESULT =null;
		If i = (If)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = i; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // stmt ::= while_stmt 
            {
              Stmt RESULT =null;
		While w = (While)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = w; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // stmt ::= read_stmt 
            {
              Stmt RESULT =null;
		Read r = (Read)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = r; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= print_stmt 
            {
              Stmt RESULT =null;
		Print p = (Print)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = p; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= bloque 
            {
              Stmt RESULT =null;
		Bloque b = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = b; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmt ::= asignacion 
            {
              Stmt RESULT =null;
		Asignacion a = (Asignacion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = a; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // stmt ::= return_stmt 
            {
              Stmt RESULT =null;
		Return r = (Return)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = r; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("stmt",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // declaracion_variable ::= VAR tipo DOS_PUNTOS ID PUNTO_Y_COMA 
            {
              DecVar RESULT =null;
		T t = (T)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new DecVar(t, id.lexema, null); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("declaracion_variable",6, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // declaracion_variable ::= VAR tipo DOS_PUNTOS ID IGUAL expr PUNTO_Y_COMA 
            {
              DecVar RESULT =null;
		T t = (T)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-5)).value;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new DecVar(t, id.lexema, e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("declaracion_variable",6, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // declaracion_funcion ::= FUNC tipo DOS_PUNTOS ID PARENTESIS_APERTURA params_opt PARENTESIS_CIERRE bloque 
            {
              DecFuncion RESULT =null;
		T t = (T)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-6)).value;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-4)).value;
		List<Parametro> ps = (List<Parametro>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		Bloque b = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new DecFuncion(t, id.lexema, ps, b); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("declaracion_funcion",7, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // tipo ::= INT 
            {
              T RESULT =null;
		 RESULT = new TipoBasico("int"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("tipo",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // tipo ::= REAL 
            {
              T RESULT =null;
		 RESULT = new TipoBasico("real"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("tipo",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // tipo ::= BOOL 
            {
              T RESULT =null;
		 RESULT = new TipoBasico("bool"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("tipo",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // tipo ::= VOID 
            {
              T RESULT =null;
		 RESULT = new TipoBasico("void"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("tipo",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // tipo ::= ARRAY dimensiones OF tipo 
            {
              T RESULT =null;
		List<Integer> ds = (List<Integer>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		T t = (T)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new TipoArray(ds, t); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("tipo",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // dimensiones ::= dimensiones CORCHETE_APERTURA NUM CORCHETE_CIERRE 
            {
              List<Integer> RESULT =null;
		List<Integer> ds = (List<Integer>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		alex.TokenValue n = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 ds.add(Integer.parseInt(n.lexema)); RESULT = ds; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("dimensiones",9, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // dimensiones ::= CORCHETE_APERTURA NUM CORCHETE_CIERRE 
            {
              List<Integer> RESULT =null;
		alex.TokenValue n = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		
                   List<Integer> l = new ArrayList<Integer>();
                   l.add(Integer.parseInt(n.lexema));
                   RESULT = l;
                 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("dimensiones",9, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // params_opt ::= lista_params 
            {
              List<Parametro> RESULT =null;
		List<Parametro> lp = (List<Parametro>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = lp; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("params_opt",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // params_opt ::= 
            {
              List<Parametro> RESULT =null;
		 RESULT = new ArrayList<Parametro>(); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("params_opt",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // lista_params ::= lista_params COMA param 
            {
              List<Parametro> RESULT =null;
		List<Parametro> lp = (List<Parametro>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		Parametro p = (Parametro)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 lp.add(p); RESULT = lp; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_params",11, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // lista_params ::= param 
            {
              List<Parametro> RESULT =null;
		Parametro p = (Parametro)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		
                    List<Parametro> l = new ArrayList<Parametro>();
                    l.add(p);
                    RESULT = l;
                  
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_params",11, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // param ::= VAR tipo DOS_PUNTOS ID 
            {
              Parametro RESULT =null;
		T t = (T)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Parametro(t, id.lexema, false); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("param",12, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // param ::= VAR tipo DOS_PUNTOS AMPERSAND ID 
            {
              Parametro RESULT =null;
		T t = (T)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Parametro(t, id.lexema, true); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("param",12, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // bloque ::= LLAVE_APERTURA lista_stmt LLAVE_CIERRE 
            {
              Bloque RESULT =null;
		List<Stmt> ls = (List<Stmt>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Bloque(ls); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("bloque",4, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // lista_stmt ::= lista_stmt stmt 
            {
              List<Stmt> RESULT =null;
		List<Stmt> ls = (List<Stmt>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 ls.add(s); RESULT = ls; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_stmt",5, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // lista_stmt ::= 
            {
              List<Stmt> RESULT =null;
		 RESULT = new ArrayList<Stmt>(); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_stmt",5, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // asignacion ::= lhs IGUAL expr PUNTO_Y_COMA 
            {
              Asignacion RESULT =null;
		E l = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Asignacion(l, e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("asignacion",13, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // lhs ::= ID 
            {
              E RESULT =null;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Id(id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lhs",14, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // lhs ::= lhs CORCHETE_APERTURA expr CORCHETE_CIERRE 
            {
              E RESULT =null;
		E l = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new AccesoArray(l, e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lhs",14, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // if_stmt ::= IF PARENTESIS_APERTURA expr PARENTESIS_CIERRE bloque 
            {
              If RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		Bloque b = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new If(e, b, null); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("if_stmt",15, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // if_stmt ::= IF PARENTESIS_APERTURA expr PARENTESIS_CIERRE bloque ELSE bloque 
            {
              If RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-4)).value;
		Bloque b1 = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		Bloque b2 = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new If(e, b1, b2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("if_stmt",15, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // while_stmt ::= WHILE PARENTESIS_APERTURA expr PARENTESIS_CIERRE bloque 
            {
              While RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		Bloque b = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new While(e, b); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("while_stmt",16, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // read_stmt ::= READ PARENTESIS_APERTURA ID PARENTESIS_CIERRE PUNTO_Y_COMA 
            {
              Read RESULT =null;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		 RESULT = new Read(id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("read_stmt",17, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // print_stmt ::= PRINT PARENTESIS_APERTURA expr PARENTESIS_CIERRE PUNTO_Y_COMA 
            {
              Print RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		 RESULT = new Print(e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("print_stmt",18, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // return_stmt ::= RETURN expr PUNTO_Y_COMA 
            {
              Return RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Return(e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("return_stmt",19, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // return_stmt ::= RETURN PUNTO_Y_COMA 
            {
              Return RESULT =null;
		 RESULT = new Return(null); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("return_stmt",19, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr ::= expr_or 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr",20, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr_or ::= expr_or OR expr_and 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.OR, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_or",21, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr_or ::= expr_and 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_or",21, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr_and ::= expr_and AND expr_rel 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.AND, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_and",22, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr_and ::= expr_rel 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_and",22, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr_rel ::= expr_rel MENOR expr_add 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.MENOR, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_rel",23, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr_rel ::= expr_rel MAYOR expr_add 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.MAYOR, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_rel",23, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr_rel ::= expr_rel IGUALDAD expr_add 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.IGUALDAD, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_rel",23, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr_rel ::= expr_add 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_rel",23, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr_add ::= expr_add SUMA expr_mul 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.SUMA, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_add",24, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr_add ::= expr_add RESTA expr_mul 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.RESTA, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_add",24, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr_add ::= expr_mul 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_add",24, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr_mul ::= expr_mul MULTIPLICACION expr_unaria 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.MUL, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_mul",25, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr_mul ::= expr_mul DIVISION expr_unaria 
            {
              E RESULT =null;
		E e1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpBinaria(KindE.DIV, e1, e2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_mul",25, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr_mul ::= expr_unaria 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_mul",25, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr_unaria ::= RESTA expr_unaria 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new ExpUnaria(KindE.MENOS_UNARIO, e); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_unaria",26, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr_unaria ::= expr_base 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_unaria",26, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr_base ::= NUM 
            {
              E RESULT =null;
		alex.TokenValue n = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Num(n.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",27, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr_base ::= NUM_REAL 
            {
              E RESULT =null;
		alex.TokenValue n = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new NumReal(n.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",27, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr_base ::= TRUE 
            {
              E RESULT =null;
		 RESULT = new Bool(true); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",27, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr_base ::= FALSE 
            {
              E RESULT =null;
		 RESULT = new Bool(false); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",27, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr_base ::= lhs 
            {
              E RESULT =null;
		E l = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = l; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",27, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr_base ::= ID PARENTESIS_APERTURA args_opt PARENTESIS_CIERRE 
            {
              E RESULT =null;
		alex.TokenValue id = (alex.TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		List<E> as = (List<E>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new LlamadaFuncion(id.lexema, as); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",27, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr_base ::= PARENTESIS_APERTURA expr PARENTESIS_CIERRE 
            {
              E RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = e; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("expr_base",27, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // args_opt ::= lista_args 
            {
              List<E> RESULT =null;
		List<E> la = (List<E>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = la; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("args_opt",28, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // args_opt ::= 
            {
              List<E> RESULT =null;
		 RESULT = new ArrayList<E>(); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("args_opt",28, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // lista_args ::= lista_args COMA expr 
            {
              List<E> RESULT =null;
		List<E> la = (List<E>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 la.add(e); RESULT = la; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_args",29, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // lista_args ::= expr 
            {
              List<E> RESULT =null;
		E e = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		
                  List<E> l = new ArrayList<E>();
                  l.add(e);
                  RESULT = l;
                
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("lista_args",29, RESULT);
            }
          return CUP$ConstructorAST$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ConstructorAST$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ConstructorAST$do_action(
    int                        CUP$ConstructorAST$act_num,
    java_cup.runtime.lr_parser CUP$ConstructorAST$parser,
    java.util.Stack            CUP$ConstructorAST$stack,
    int                        CUP$ConstructorAST$top)
    throws java.lang.Exception
    {
              return CUP$ConstructorAST$do_action_part00000000(
                               CUP$ConstructorAST$act_num,
                               CUP$ConstructorAST$parser,
                               CUP$ConstructorAST$stack,
                               CUP$ConstructorAST$top);
    }
}

